
services:
#  db:
#    image: mysql:latest
#
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: world
#
#    ports:
#      - "3306:3306"
#
##   Shifts the world.sql file into the container directory. It then gets auto exectuted on load, seeding the db
#    volumes:
#      - ./world.sql:/docker-entrypoint-initdb.d/world.sql

  java:
    build: .
    #    Stops the java container running ahead without the database running
#    depends_on:
#      - db