name: Workflow for SEM group project
on: push

jobs:
  build:
    name: Build, Test Project, Run Docker,
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Package and run with docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

#        Will test data handling
      - name: Unit Tests
        run: mvn -Dtest=DataProcessingTest test
      - name: Integrated Tests
        run: mvn -Dtest=Test test