name: Workflow for SEM group project
on: push

jobs:
  build:
    name: Build, Test Project, Run Docker,
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: world
        ports:
          - 3306

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Seed Database
        run:
          mysql -u root -proot world < world.sql
      - name: Test Database
        run:
          mysql -u root -proot || SELECT * FROM city LIMIT 1

      - name: Package and run with docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

#        Will test data handling
      - name: Unit Tests
        run: mvn -Dtest=DataProcessingTest test
      - name: Integrated Tests
        run: mvn -Dtest=Test test